/*
** phases.c
**	Contains the bomb phases.
*/

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define PHASE_SIX_CONST 3
#define DEMO_ONE 10
#define DEMO_TWO 11

int main(int argc, char** argv) {
	char* fortunes[] = {
		"A bird in the hand is worth what it will bring.",
		"A conclusion is simply the place where someone got tired of thinking.",
		"A physicist is an atom's way of knowing about atoms. -- George Wald",
		"A radioactive cat has eighteen half-lives.",
		"A tautology is a thing which is tautological.",
		"An elephant is a mouse with an operating system.",
		"Any small object that is accidentally dropped will hide under a larger object",
		"Anything worth doing is worth overdoing",
		"Art is anything you can get away with. -- Marshall McLuhan.",
		"Ban the bomb. Save the world for conventional warfare.",
		"Be careful of reading health books, you might die of a misprint.-- Mark Twain",
		"Beware of low-flying butterflies.",
		"Blessed are the young for they shall inherit the national debt.",
		"Confidence is the feeling you have before you understand the situation.",
		"Conscience is a mother-in-law whose visit never ends. -- H. L. Mencken",
		"Dare to be naive. -- R. Buckminster Fuller",
		"Deliver yesterday, code today, think tomorrow.",
		"Don't change the reason, just change the excuses! -- Joe Cointment",
		"Don't get even -- get odd!",
		"Ducharme's Precept: Opportunity always knocks at the least opportune moment.",
		"Experience varies directly with equipment ruined.",
		"Fairy Tale, n.: A horror story to prepare children for the newspapers.",
		"Five is a sufficiently close approximation to infinity. -- Robert Firth",
		"For a man to truly understand rejection, he must first be ignored by a cat.",
		"Happiness is having a scratch for every itch. -- Ogden Nash",
		"Hard work may not kill you, but why take chances?",
		"History repeats itself. That's one thing wrong with history.",
		"How long a minute is depends on which side of the bathroom door you're on.",
		"How wonderful opera would be if there were no singers.",
		"I bet the human brain is a kludge. -- Marvin Minsky",
		"I doubt, therefore I might be.",
		"I refuse to have a battle of wits with an unarmed person.",
		"I used to think I was indecisive, but now I'm not so sure.",
		"I'm going to live forever, or die trying! -- Spider Robinson",
		"I'm prepared for all emergencies but totally unprepared for everyday life.",
		"I've enjoyed just about as much of this as I can stand.",
		"If I don't see you in the future, I'll see you in the pasture.",
		"If I had any humility I would be perfect. -- Ted Turner",
		"If all the world's a stage, I want to operate the trap door. -- Paul Beatty",
		"If at first you don't succeed, redefine success.",
		"If dolphins are so smart, why did Flipper work for television?",
		"If everything is coming your way then you're in the wrong lane.",
		"If time heals all wounds, how come the belly button stays the same?",
		"If two wrongs don't make a right, try three. -- Laurence J. Peter",
		"If we were meant to fly, we wouldn't keep losing our luggage.",
		"If you can't learn to do it well, learn to enjoy doing it badly.",
		"If you don't care where you are, then you ain't lost.",
		"If you have a procedure with 10 parameters, you probably missed some.",
		"If you keep anything long enough, you can throw it away.",
		"If you only have a hammer, you tend to see every problem as a nail.-- Maslow",
		"If you're right 90% of the time, why quibble about the remaining 3%?",
		"It was a book to kill time for those who liked it better dead.",
		"It's always darkest just before it gets pitch black.",
		"It's illegal in Wilbur, Washington, to ride an ugly horse.",
		"Laughter is the closest distance between two people. -- Victor Borge",
		"Let He who taketh the Plunge Remember to return it by Tuesday.",
		"Life is like a simile.",
		"Line Printer paper is strongest at the perforations.",
		"Lubarsky's Law of Cybernetic Entomology: There's always one more bug.",
		"Mother is the invention of necessity.",
		"Never call a man a fool. Borrow from him.",
		"New systems generate new problems.",
		"Nondeterminism means never having to say you are wrong.",
		"Nothing recedes like success. -- Walter Winchell",
		"Nuclear war can ruin your whole compile. -- Karl Lehenbauer",
		"Ogden's Law: The sooner you fall behind, the more time you have to catch up.",
		"One seldom sees a monument to a committee.",
		"Only adults have difficulty with childproof caps.",
		"Overload -- core meltdown sequence initiated.",
		"Paranoia is simply an optimistic outlook on life.",
		"Parker's Law: Beauty is only skin deep, but ugly goes clean to the bone.",
		"People will buy anything that's one to a customer.",
		"Pure drivel tends to drive ordinary drivel off the TV screen.",
		"Reality is for those who can't face Science Fiction.",
		"Really ?? What a coincidence, I'm shallow too!!",
		"Sattinger's Law: It works better if you plug it in.",
		"Save the whales. Collect the whole set.",
		"Smoking is one of the leading causes of statistics. -- Fletcher Knebel",
		"Spare no expense to save money on this one. -- Samuel Goldwyn",
		"Sweater, n.: A garment worn by a child when its mother feels chilly.",
		"The best cure for insomnia is to get a lot of sleep. -- W. C. Fields",
		"The best thing about growing older is that it takes such a long time.",
		"The light at the end of the tunnel is the headlight of an approaching train.",
		"The older a man gets, the farther he had to walk to school as a boy.",
		"The only way to get rid of a temptation is to yield to it. -- Oscar Wilde",
		"The opposite of a profound truth may well be another profound truth. -- Bohr",
		"The world is coming to an end. Please log off.",
		"There are three kinds of lies: Lies, Damn Lies, and Statistics. -- Disraeli",
		"There is no time like the pleasant.",
		"There's a fine line between courage and foolishness. Too bad it's not a fence",
		"Those who can, do. Those who can't, simulate.",
		"Time is an illusion; lunchtime, doubly so. -- Ford Prefect",
		"Time is nature's way of making sure that everything doesn't happen at once.",
		"To be intoxicated is to feel sophisticated but not be able to say it.",
		"To err is human, to moo bovine.",
		"To generalize is to be an idiot. -- William Blake",
		"Too clever is dumb. -- Ogden Nash",
		"Too much of everything is just enough. -- Bob Wier",
		"Universe, n.: The problem.",
		"Virginia law forbids bathtubs in the house; tubs must be kept in the yard.",
		"Wasting time is an important part of living.",
		"We can predict everything, except the future.",
		"We have met the enemy, and he is us. -- Walt Kelly",
		"Wethern's Law: Assumption is the mother of all screw-ups.",
		"What is a magician but a practising theorist? -- Obi-Wan Kenobi",
		"What the large print giveth, the small print taketh away.",
		"What this country needs is a good five cent microcomputer.",
		"What this world needs is a good five-dollar plasma weapon.",
		"What's another word for Thesaurus? -- Steven Wright",
		"Where there's a will, there's an Inheritance Tax.",
		"Which is worse: ignorance or apathy? Who knows? Who cares?",
		"Who messed with my anti-paranoia shot?",
		"Yes, but which self do you want to be?",
		"You can't make a program without broken egos.",
		"You cannot achieve the impossible without attempting the absurd.",
		"You cannot kill time without injuring eternity.",
		"You have the capacity to learn from mistakes. You'll learn a lot today.",
		"Your life would be very empty if you had nothing to regret.",
		"f u cn rd ths, u cn gt a gd jb n cmptr prgrmmng.",
		0
	};

	char* words[] = {
		"abovementioned",
		"aforementioned",
		"antiperspirant",
		"astrophysicist",
		"cardiovascular",
		"characteristic",
		"chromatography",
		"circumlocution",
		"circumstantial",
		"classification",
		"classificatory",
		"claustrophobia",
		"claustrophobic",
		"committeewoman",
		"comprehensible",
		"concessionaire",
		"congratulatory",
		"consanguineous",
		"conspiratorial",
		"contradistinct",
		"controvertible",
		"counterbalance",
		"counterexample",
		"differentiable",
		"diffractometer",
		"disciplinarian",
		"discriminatory",
		"extemporaneous",
		"featherbedding",
		"ferromagnetism",
		"handicraftsman",
		"histochemistry",
		"hydrochemistry",
		"implementation",
		"inapproachable",
		"incommensurate",
		"incommunicable",
		"incompressible",
		"inconsiderable",
		"incontrollable",
		"indecipherable",
		"indecomposable",
		"indestructible",
		"indeterminable",
		"indiscoverable",
		"indiscriminate",
		"infrastructure",
		"insuppressible",
		"insurmountable",
		"intelligentsia",
		"interferometer",
		"interpretation",
		"intramolecular",
		"irreconcilable",
		"irreproachable",
		"irreproducible",
		"macromolecular",
		"macroprocessor",
		"macrostructure",
		"morphophonemic",
		"multiplication",
		"multiplicative",
		"neuropathology",
		"nitroglycerine",
		"optoelectronic",
		"organometallic",
		"orthophosphate",
		"paralinguistic",
		"parallelepiped",
		"parapsychology",
		"phosphorescent",
		"physiochemical",
		"polysaccharide",
		"predisposition",
		"presentational",
		"prestidigitate",
		"presupposition",
		"proprioception",
		"proprioceptive",
		"psychoacoustic",
		"psychoanalysis",
		"psychoanalytic",
		"quintessential",
		"radioastronomy",
		"radiochemistry",
		"radiotelegraph",
		"radiotelephone",
		"reconnaissance",
		"representative",
		"septuagenarian",
		"servomechanism",
		"slaughterhouse",
		"staphylococcus",
		"superintendent",
		"teleconference",
		"teleprocessing",
		"tetrafluouride",
		"transcendental",
		"transformation",
		"transportation",
		"unidimensional",
		"unidirectional",
		"verisimilitude",
		0
	};
	
	printf("words[11]: %s\n", words[11]);
	printf("words[11+1]+3: %s\n", words[11+1]+3);
	return 0;
}
